name: Build and test wheels nightly and for new releases

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"
  schedule:
    - cron: "0 06 * * *"

jobs:
  build-test-wheels:
    name: build-test-wheel python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build wheels
        uses: ./.github/actions/wheel_build
        with:
          python-version: ${{ matrix.python-version }}
          wheel-name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
      - name: Test wheels
        uses: ./.github/actions/wheel_test
        with:
          python-version: ${{ matrix.python-version }}
          wheel-name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}

  publish-wheels:
    # only publish wheels on new tag
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-test-wheels
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:

      - name: Download all wheels
        uses: actions/download-artifact@v7
        with:
          path: wheels

      - name: Flatten wheel folders in one directory
        run: |
          # Move all wheels from subfolders to the main folder and delete empty folders
          find wheels -name '*.whl' -exec mv {} wheels/ \;
          find wheels -type d -empty -delete

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: wheels
